import { useCallback, useEffect, useState } from "react";
import { ArrowUpRight, Building2, Edit3, Plus, Trash2 } from "lucide-react";
import { CompanyLogo } from "@/components/JobCard";
import { api, jsonBody, type Company } from "@/lib/api";
import { CompanyEditor } from "./AdminForms";

export default function AdminCompanies() {
  const [companies, setCompanies] = useState<Company[]>([]); const [editing, setEditing] = useState<Company | null>(null); const [creating, setCreating] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const result = await api<{ companies: Company[] }>("/api/gm/admin/companies"); setCompanies(result.companies); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Company profiles could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(data: Record<string, unknown>, id?: number) { await api(id ? `/api/gm/admin/companies/${id}` : "/api/gm/admin/companies", { method: id ? "PUT" : "POST", body: jsonBody(data) }); setEditing(null); setCreating(false); await load(); }
  async function remove(company: Company) { if (!window.confirm(`Delete the profile for ${company.name}? Linked jobs will keep their saved company name.`)) return; await api(`/api/gm/admin/companies/${company.id}`, { method: "DELETE" }); await load(); }
  return <div className="admin-section"><div className="admin-page-title"><div><span className="eyebrow muted-eyebrow">ORGANISATION DETAILS</span><h1>Company profiles</h1><p>Keep company descriptions, websites and logos consistent across listings.</p></div><button className="primary-button" onClick={() => { setCreating(true); setEditing(null); }}><Plus size={16} />Add company</button></div>{error && <p className="admin-alert error-alert">{error}</p>}{creating && <div className="admin-panel edit-panel"><CompanyEditor onCancel={() => setCreating(false)} onSave={data => save(data)} /></div>}{editing && <div className="admin-panel edit-panel"><CompanyEditor initial={editing} onCancel={() => setEditing(null)} onSave={data => save(data, editing.id)} /></div>}{loading ? <div className="admin-loading-inline">Loading companies…</div> : companies.length ? <div className="company-admin-list">{companies.map(company => <article className="admin-list-card" key={company.id}><CompanyLogo name={company.name} imageUrl={company.logoUrl} size="large" /><div className="admin-list-card-main"><h3>{company.name}</h3><p>{company.location || "Location not listed"}</p><small>{company.description ? `${company.description.slice(0, 140)}${company.description.length > 140 ? "…" : ""}` : "No description added"}</small></div><div className="admin-card-actions"><a href={`/companies/${company.id}`} className="icon-button" title="View public profile" aria-label="View public company profile"><ArrowUpRight size={15} /></a><button className="icon-button" title="Edit company" aria-label="Edit company" onClick={() => { setEditing(company); setCreating(false); }}><Edit3 size={15} /></button><button className="icon-button danger-icon" title="Delete company" aria-label="Delete company" onClick={() => void remove(company)}><Trash2 size={15} /></button></div></article>)}</div> : !creating && !editing ? <div className="admin-empty"><Building2 size={24} /><h2>No company profiles yet.</h2><p>You can add a profile when you have confirmed details and branding.</p></div> : null}</div>;
}
