import { useCallback, useEffect, useState } from "react";
import { ArrowDownToLine, ArrowUpRight, Check, Edit3, Plus, Send, Trash2 } from "lucide-react";
import { api, jsonBody, type Company, type Job } from "@/lib/api";
import { JobEditor, type JobDraft } from "./AdminForms";

export default function AdminJobs({ onChanged }: { onChanged: () => void }) {
  const [jobs, setJobs] = useState<Array<Job & { status: "draft" | "published" }>>([]);
  const [companies, setCompanies] = useState<Company[]>([]);
  const [editing, setEditing] = useState<(Job & { status: "draft" | "published" }) | null>(null);
  const [creating, setCreating] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [jobData, companyData] = await Promise.all([api<{ jobs: Array<Job & { status: "draft" | "published" }> }>("/api/gm/admin/jobs"), api<{ companies: Company[] }>("/api/gm/admin/companies")]); setJobs(jobData.jobs); setCompanies(companyData.companies); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load jobs."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(data: JobDraft, id?: number) { const payload = { ...data, companyId: data.companyId ? Number(data.companyId) : null }; await api(id ? `/api/gm/admin/jobs/${id}` : "/api/gm/admin/jobs", { method: id ? "PUT" : "POST", body: jsonBody(payload) }); setEditing(null); setCreating(false); await load(); onChanged(); }
  async function setStatus(job: Job & { status: "draft" | "published" }, status: "draft" | "published") { await api(`/api/gm/admin/jobs/${job.id}`, { method: "PUT", body: jsonBody({ status }) }); await load(); onChanged(); }
  async function remove(job: Job) { if (!window.confirm(`Permanently delete “${job.title}” and its saved likes/saves?`)) return; await api(`/api/gm/admin/jobs/${job.id}`, { method: "DELETE" }); await load(); onChanged(); }
  return <div className="admin-section"><div className="admin-page-title"><div><span className="eyebrow muted-eyebrow">THE PUBLIC BOARD</span><h1>Job listings</h1><p>Add, edit or change visibility. Public pages show published listings only.</p></div><button className="primary-button" onClick={() => { setCreating(true); setEditing(null); }}><Plus size={16} />Add job</button></div>{error && <p className="admin-alert error-alert">{error}</p>}{creating && <div className="admin-panel edit-panel"><JobEditor companies={companies} onCancel={() => setCreating(false)} onSave={data => save(data)} /></div>}{editing && <div className="admin-panel edit-panel"><JobEditor initial={editing} companies={companies} onCancel={() => setEditing(null)} onSave={data => save(data, editing.id)} /></div>}{loading ? <div className="admin-loading-inline">Loading listings…</div> : jobs.length ? <div className="admin-list">{jobs.map(job => <article className="admin-list-card" key={job.id}><div className="admin-list-card-main"><span className={`status-label ${job.status === "published" ? "status-published" : "status-draft"}`}><span />{job.status === "published" ? "Published" : "Unpublished"}</span><h3>{job.title}</h3><p>{job.companyName || "Company not specified"}{job.location ? ` · ${job.location}` : ""}</p><small>{job.publishedAt ? `Published ${new Date(job.publishedAt).toLocaleDateString()}` : `Created ${job.createdAt ? new Date(job.createdAt).toLocaleDateString() : ""}`}</small></div><div className="admin-card-actions"><button className="icon-button" title="Edit listing" aria-label="Edit listing" onClick={() => { setEditing(job); setCreating(false); }}><Edit3 size={15} /></button><button className={`icon-button ${job.status === "published" ? "status-action-on" : ""}`} title={job.status === "published" ? "Unpublish" : "Publish"} aria-label={job.status === "published" ? "Unpublish" : "Publish"} onClick={() => void setStatus(job, job.status === "published" ? "draft" : "published")}>{job.status === "published" ? <ArrowDownToLine size={16} /> : <Send size={15} />}</button><button className="icon-button danger-icon" title="Delete listing" aria-label="Delete listing" onClick={() => void remove(job)}><Trash2 size={15} /></button></div></article>)}</div> : !creating && !editing ? <div className="admin-empty"><BriefcaseBusinessIcon /><h2>No jobs yet.</h2><p>Start with a verified opportunity. You can publish it now or save it as a draft.</p><button className="secondary-button" onClick={() => setCreating(true)}>Add the first job <ArrowUpRight size={14} /></button></div> : null}</div>;
}
function BriefcaseBusinessIcon() { return <span className="admin-empty-symbol"><Check size={20} /></span>; }
