import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, ArrowUpRight, CalendarClock, Edit3, Play, Plus, Radio, Rss, Trash2, TriangleAlert } from "lucide-react";
import { api, jsonBody } from "@/lib/api";
import { SourceEditor, type SourceRecord } from "./AdminForms";

type Schedule = { enabled: boolean; cronExpression: string; lastRunAt: string | null; heartbeatTaskUid?: string | null };
type Overview = { schedule: Schedule };
const schedules = [
  { cron: "0 0 6 * * *", label: "Daily · 9:00 AM Tanzania time" },
  { cron: "0 0 6,15 * * *", label: "Twice daily · 9:00 AM and 6:00 PM Tanzania time" },
  { cron: "0 0 0,12 * * *", label: "Twice daily · 3:00 AM and 3:00 PM Tanzania time" },
];

export default function AdminSources({ onChanged }: { onChanged: () => void }) {
  const [sources, setSources] = useState<SourceRecord[]>([]); const [editing, setEditing] = useState<SourceRecord | null>(null); const [creating, setCreating] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [runningId, setRunningId] = useState<number | null>(null);
  const [enabled, setEnabled] = useState(false); const [cron, setCron] = useState(schedules[0].cron); const [scheduleSaving, setScheduleSaving] = useState(false); const [scheduleMessage, setScheduleMessage] = useState(""); const [lastRunAt, setLastRunAt] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const [sourceData, overview] = await Promise.all([api<{ sources: SourceRecord[] }>("/api/gm/admin/sources"), api<Overview>("/api/gm/admin/overview")]); setSources(sourceData.sources); setEnabled(overview.schedule.enabled); setCron(overview.schedule.cronExpression || schedules[0].cron); setLastRunAt(overview.schedule.lastRunAt); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Tracked sources could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(data: Record<string, unknown>, id?: number) { await api(id ? `/api/gm/admin/sources/${id}` : "/api/gm/admin/sources", { method: id ? "PUT" : "POST", body: jsonBody(data) }); setEditing(null); setCreating(false); setMessage(""); await load(); onChanged(); }
  async function toggle(source: SourceRecord) { await api(`/api/gm/admin/sources/${source.id}`, { method: "PUT", body: jsonBody({ name: source.name, type: source.type, url: source.url, isActive: !source.isActive, settings: source.settings ?? {} }) }); await load(); onChanged(); }
  async function remove(source: SourceRecord) { if (!window.confirm(`Delete tracked source “${source.name}”? Previously collected review records stay in the queue.`)) return; await api(`/api/gm/admin/sources/${source.id}`, { method: "DELETE" }); await load(); onChanged(); }
  async function run(source: SourceRecord) { setRunningId(source.id); setMessage(""); setError(""); try { const result = await api<{ result: { candidatesFound: number; newPending: number; duplicatesFlagged: number; alreadySeen: number; skipped: number } }>(`/api/gm/admin/sources/${source.id}/run`, { method: "POST", body: "{}" }); const report = result.result; setMessage(`${source.name}: ${report.candidatesFound} listings found · ${report.newPending} sent to review · ${report.duplicatesFlagged} flagged for duplicate review${report.alreadySeen ? ` · ${report.alreadySeen} already seen` : ""}${report.skipped ? ` · ${report.skipped} skipped (no title)` : ""}. Nothing was published.`); await load(); onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Source run failed."); await load(); } finally { setRunningId(null); } }
  async function saveSchedule(event: React.FormEvent) { event.preventDefault(); setScheduleSaving(true); setScheduleMessage(""); setError(""); try { const result = await api<{ schedule: Schedule }>("/api/gm/admin/schedule", { method: "POST", body: jsonBody({ enabled, cronExpression: cron }) }); setEnabled(result.schedule.enabled); setScheduleMessage(enabled ? "Scheduled scanning is on. Collected listings still require review." : "Scheduled scanning is paused."); await load(); onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Schedule could not be saved."); } finally { setScheduleSaving(false); } }
  return <div className="admin-section"><div className="admin-page-title"><div><span className="eyebrow muted-eyebrow">SOURCE → REVIEW → APPROVAL</span><h1>Tracked sources</h1><p>Add feeds and career pages. Collected listings are never published automatically.</p></div><button className="primary-button" onClick={() => { setCreating(true); setEditing(null); }}><Plus size={16} />Add source</button></div>{error && <p className="admin-alert error-alert"><TriangleAlert size={15} />{error}</p>}{message && <p className="admin-alert success-alert"><Radio size={15} />{message}</p>}{creating && <div className="admin-panel edit-panel"><SourceEditor onCancel={() => setCreating(false)} onSave={data => save(data)} /></div>}{editing && <div className="admin-panel edit-panel"><SourceEditor initial={editing} onCancel={() => setEditing(null)} onSave={data => save(data, editing.id)} /></div>}{loading ? <div className="admin-loading-inline">Loading sources…</div> : sources.length ? <div className="source-list">{sources.map(source => <article key={source.id} className={`source-card ${source.isActive ? "" : "source-inactive"}`}><div className="source-card-top"><span className="source-type-icon"><Rss size={17} /></span><span className={`status-label ${source.isActive ? "status-published" : "status-draft"}`}><span />{source.isActive ? "Active" : "Inactive"}</span><label className="source-toggle"><input type="checkbox" checked={source.isActive} onChange={() => void toggle(source)} /><span>{source.isActive ? "On" : "Off"}</span></label></div><h3>{source.name}</h3><a className="source-url" href={source.url} target="_blank" rel="noreferrer">{source.url}<ArrowUpRight size={13} /></a><div className="source-card-stats"><span><strong>{source.totalJobsFound}</strong> new to review</span><span>{source.lastRunAt ? new Date(source.lastRunAt).toLocaleString() : "Never run"}</span></div>{source.lastRunError && <p className="source-error"><AlertTriangle size={14} />{source.lastRunError}</p>}<div className="source-card-actions"><button className="secondary-button" onClick={() => void run(source)} disabled={runningId === source.id}><Play size={14} />{runningId === source.id ? "Running…" : "Run now"}</button><button className="icon-button" title="Edit source" aria-label="Edit source" onClick={() => { setEditing(source); setCreating(false); }}><Edit3 size={15} /></button><button className="icon-button danger-icon" title="Delete source" aria-label="Delete source" onClick={() => void remove(source)}><Trash2 size={15} /></button></div></article>)}</div> : !creating && !editing ? <div className="admin-empty"><Rss size={22} /><h2>No sources yet.</h2><p>Connect an RSS feed, JSON API, career page or public static jobs page to begin collecting.</p><button className="secondary-button" onClick={() => setCreating(true)}>Add your first source <ArrowUpRight size={14} /></button></div> : null}
    <section className="admin-panel schedule-panel"><div className="panel-heading"><div><span className="eyebrow muted-eyebrow">AUTOMATIC SCANNING</span><h2><CalendarClock size={19} />Scan schedule</h2></div><span className={`status-label ${enabled ? "status-published" : "status-draft"}`}><span />{enabled ? "Enabled" : "Paused"}</span></div><p>Active sources are checked on the selected schedule and new listings go to the review queue. All schedule times are East Africa Time (EAT).</p><form className="schedule-form" onSubmit={event => void saveSchedule(event)}><label>Frequency<select value={cron} onChange={event => setCron(event.target.value)}>{schedules.map(option => <option value={option.cron} key={option.cron}>{option.label}</option>)}</select></label><label className="schedule-checkbox"><input type="checkbox" checked={enabled} onChange={event => setEnabled(event.target.checked)} />Enable automatic scanning</label><button className="primary-button" type="submit" disabled={scheduleSaving}>{scheduleSaving ? "Saving…" : "Save schedule"}<ArrowUpRight size={14} /></button></form>{scheduleMessage && <p className="schedule-message">{scheduleMessage}</p>}{lastRunAt && <small className="field-help">Last scheduled scan: {new Date(lastRunAt).toLocaleString()}</small>}<div className="schedule-footnote"><AlertTriangle size={14} /><span>Scheduled callbacks run on the published site. Publish the approved build before relying on automatic scans. “Run now” is available here in the meantime.</span></div></section>
  </div>;
}
